# Generated by Django 4.2.6 on 2024-04-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_weight_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField(default=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_location', to='inventory_management.storagelocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_on_shelf', to='inventory_management.product')),
            ],
        ),
    ]
