# Generated by Django 4.2.6 on 2024-04-12 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManagementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('WAITING', 'waiting'), ('PARSING', 'parsing'), ('OK', 'ok')], default='WAITING', max_length=30)),
                ('result', models.JSONField(default={})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inventory_management_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
